title: Read, Write, Code
email: mikekelly@rockweb.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  The online home of Mike Kelly. Mike is a programmer, cloud native engineer, scrum master, ux designer and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: /page-:num/

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: thisismikekelly
    github:  mike-w-kelly
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: mikewkelly
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

defaults:
- scope:
    path: "assets/img"
  values:
    image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/